# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Î»x.x
email: djl329@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  My assorted ramblings, concepts that I am trying to improve my understanding
  of, and stuff that I made.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lehmacdj.github.io" # the base hostname & protocol for your site
github_username: lehmacdj
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
include: ["_tags"]
