# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UnformedDelta
email: lehmacdj@gmail.com
description: >
  The UnformedDelta is the place where my thoughts and learnings collect like
  sand and soil at a river delta. Mostly the distillation of things I've learned
  or figured out.
baseurl: "/"
url: "https://lehmacdj.github.io" # the base hostname & protocol for your site
github_username: lehmacdj
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
include: ["_tags"]
